### ISSUE TITLE
Fran-C Dubosc  

### ISSUE THREAD

**Issue by Nynko** [Any0ne22/fran-c#1]
Voici des améliorations de hauts niveaux:

```C
#define sortir exit
#define avorter abort
#define tirer_la_chasse fflush
#define fermer_fichier fclose
#define dire puts
```

avenant à venir

**Comment by aeyno** [comment]
Fait : [9b771585519c6daeec83a29b88719ab767f6acf6](https://github.com/Any0ne22/fran-c/commit/9b771585519c6daeec83a29b88719ab767f6acf6)
